# Use official Python base image
FROM python:3.9-slim

# Set working directory
WORKDIR /app


# Copy the rest of the application
COPY . .

# Expose the port Flask runs on
EXPOSE 5000

# Command to run the application
CMD ["python", "flappybird.py"]